version: '3.4'

services:
    codb:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            - "ACCEPT_EULA=Y"
            - "SA_PASSWORD=6RHHShkc#Pya57Qx9"
        container_name: mssqlco
        ports:
            - "1433:1433"
    coapi:
        image: coapi
        depends_on: 
            - codb
        container_name: totalPriceAPIco
        ports:
            - "5078:80"
            - "7208:443"
    coweb:
        image: coweb
        depends_on: 
            - coapi
        container_name: totalPriceWEBco
        ports:
            - "8081:8081"