version: '3.4'

services:            
    POdb:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            - "ACCEPT_EULA=Y"
            - "SA_PASSWORD=6RHHShkc#Pya57Qx9"
        container_name: mssqlPO
        ports:
            - "1434:1433"
    POapi:
        image: poapi
        depends_on: 
            - POdb
        container_name: totalPriceAPIPO
        ports:
            - "5077:80"
            - "7208:443"
    POweb:
        image: poweb
        depends_on: 
            - POapi
        container_name: totalPriceWEBPO
        ports:
            - "8080:8080"